on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: asdf-vm/asdf

    - name: Test
      run: |
        . asdf.sh
        asdf plugin-test binnacle https://github.com/${{ github.repository }}.git 'binnacle --version'
